import xlsx from 'xlsx';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import path from 'path';
import fs from 'fs';

export const googlesheet = async (sheetNumber) => {
    let filepath;
    if(sheetNumber == 1){
        filepath = path.join(path.resolve('transaction_emails_1.xlsx'));
      }else{
        filepath = path.join(path.resolve('transaction_emails_2.xlsx'));
      }
    const workbook = xlsx.readFile(filepath);
    const sheetName = workbook.SheetNames[0];
    const workSheet = workbook.Sheets[sheetName];
    const data = xlsx.utils.sheet_to_json(workSheet);
    const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: process.env.GOOGLE_EMAIL ,
        key: process.env.GOOGLE_KEY.replace(/\\n/g, '\n'),
        scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });
    let googlesheet;
    if(sheetNumber == 1){
        googlesheet = process.env.GOOGLE_SPREADSHEET_1;
        
    }else{
        googlesheet = process.env.GOOGLE_SPREADSHEET_2;
    }
      
        
    
    const doc = new GoogleSpreadsheet(googlesheet, serviceAccountAuth);


    await doc.loadInfo();

    const sheet = doc.sheetsByIndex[0];

    await sheet.clear();

    await sheet.setHeaderRow(Object.keys(data[0]));

    await sheet.addRows(data);

    console.log("Data imported successfully");

};
